version: '3.3'

networks:
  backend:
    driver: bridge

services: 
    web_server:
        build: 
            context: ./nginx
        container_name: nginx_server
        volumes: 
                - ./php:/var/www/irwan
                - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - "8096:80"
            - "4330:433"
        networks:
            - backend
        depends_on: 
            - php

    php:
        build: 
            context: ./php
        volumes: 
            - ./php:/var/www/irwan
        container_name: php_fpm
        networks:
            - backend

